more errors...
[ 66%] Building CXX object CMakeFiles/sample_implicit.dir/sample_implicit.cpp.o
In file included from /usr/include/c++/4.9/array:35:0,
                 from /home/rana/Software/surface-reconstruction-benchmark/sample_implicit.cpp:5:
/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the